name: arboba-venv
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - beautifulsoup4
  - html5lib
  - selenium
  - webdriver-manager
  - pyogrio
  - fiona
  - nbformat
  - ipykernel
  - openpyxl